# Generated by Django 3.1 on 2020-08-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ave_rating', models.PositiveSmallIntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('super_lig_team', models.CharField(blank=True, choices=[('FB', 'FB'), ('GS', 'GS'), ('BJK', 'BJK'), ('TS', 'TS'), ('Başakşehir', 'Başakşehir'), ('Bursa', 'Bursa'), ('GB', 'GB'), ('AG', 'AG'), ('Antalya', 'Antalya'), ('Antep', 'Antep'), ('Malatya', 'Malatya'), ('Kayseri', 'Kayseri'), ('Alanya', 'Alanya'), ('Göztepe', 'Göztepe'), ('Akhisar', 'Akhisar'), ('Hatay', 'Hatay'), ('Rize', 'Rize'), ('Sivas', 'Sivas'), ('Konya', 'Konya'), ('Kasımpaşa', 'Kasımpaşa'), ('Denizli', 'Denizli'), ('Erzurum', 'Erzurum'), ('Karabük', 'Karabük'), ('Eskişehir', 'Eskişehir')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True)),
                ('position', models.CharField(blank=True, choices=[('Goal Keeper', 'Goal Keeper'), ('Defence', 'Defence'), ('Midfield', 'Midfield'), ('Striker', 'Striker')], max_length=25, null=True)),
                ('ave_rating', models.PositiveSmallIntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
